FROM julia:${image.image_name}

RUN mkdir -p ${image.julia_path}
ENV JULIA_DEPOT_PATH=${image.julia_path}

RUN mkdir -p ${image.runtime_path}
WORKDIR ${image.runtime_path}

COPY ${builtins.image_components_path}/startup.jl $JULIA_DEPOT_PATH
COPY ${builtins.image_components_path}/runtime.jl ./
COPY ${builtins.image_components_path}/dependencies.jl ./
COPY ${builtins.image_components_path}/bootstrap ./
COPY ${builtins.image_components_path}/aws-lambda-rie /usr/local/bin/aws-lambda-rie

RUN /usr/local/julia/bin/julia --startup-file=no dependencies.jl

ENTRYPOINT ["${builtins.image_components_path}/bootstrap"]
